# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import user_ops_pb2 as user__ops__pb2


class UserOpsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create_user = channel.unary_unary(
        '/UserOps/create_user',
        request_serializer=user__ops__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=user__ops__pb2.UserResponse.FromString,
        )
    self.get_user = channel.unary_unary(
        '/UserOps/get_user',
        request_serializer=user__ops__pb2.GetUserRequest.SerializeToString,
        response_deserializer=user__ops__pb2.UserResponse.FromString,
        )
    self.update_user = channel.unary_unary(
        '/UserOps/update_user',
        request_serializer=user__ops__pb2.UpdateUserRequest.SerializeToString,
        response_deserializer=user__ops__pb2.UserResponse.FromString,
        )
    self.delete_user = channel.unary_unary(
        '/UserOps/delete_user',
        request_serializer=user__ops__pb2.DeleteUserRequest.SerializeToString,
        response_deserializer=user__ops__pb2.UserResponse.FromString,
        )


class UserOpsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserOpsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create_user': grpc.unary_unary_rpc_method_handler(
          servicer.create_user,
          request_deserializer=user__ops__pb2.CreateUserRequest.FromString,
          response_serializer=user__ops__pb2.UserResponse.SerializeToString,
      ),
      'get_user': grpc.unary_unary_rpc_method_handler(
          servicer.get_user,
          request_deserializer=user__ops__pb2.GetUserRequest.FromString,
          response_serializer=user__ops__pb2.UserResponse.SerializeToString,
      ),
      'update_user': grpc.unary_unary_rpc_method_handler(
          servicer.update_user,
          request_deserializer=user__ops__pb2.UpdateUserRequest.FromString,
          response_serializer=user__ops__pb2.UserResponse.SerializeToString,
      ),
      'delete_user': grpc.unary_unary_rpc_method_handler(
          servicer.delete_user,
          request_deserializer=user__ops__pb2.DeleteUserRequest.FromString,
          response_serializer=user__ops__pb2.UserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'UserOps', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
